/// <reference types="cypress" />

describe('Testing in Demo Web Shop', () =>{
  beforeEach(()=>{
  cy.visit('/'),
  cy.visit(Cypress.env('Register_url'))

  })
   it('Visit Demo Web Shop', () =>{
    //cy.visit('/')
    cy.get('.ico-register').click()
   })
  //Sukses register custome command
  it('Testing Register success with custome command', () =>{
    //cy.visit(Cypress.env('Register_url'))
    cy.register('Isnaeni', 'Rachmawati','Isnaeni77@gmail.com','Isna123', 'Isna123', )
    cy.get('h1').contains('Register')
    //cy.get('.page-body > .buttons > .button-1').click()  
    cy.klik('.page-body > .buttons > .button-1')
    cy.get('[class="account"]').contains('Isnaeni77@gmail.com')//untuk memastikan bahwa berhasil registrasi
  })
   it ('Register with a previously used email', () =>{
     //cy.visit(Cypress.env('Register_url'))
     cy.get('h1').should('have.text', 'Register')
     cy.get('#gender-female').check()
     cy.get('#FirstName').should('be.visible').type('Isnaeni')
     cy.get('#LastName').should('be.visible').type('rachmawati')
     cy.get('#Email').should('be.visible').type('Isna@gmail.com')
     cy.get('#Password').should('be.visible').type('Isna234')
     cy.get('#ConfirmPassword').type('Isna234')
     cy.get('#register-button').click()
     cy.get('h1').contains('Register')
     //cy.get('.page-body > .buttons > .button-1').click()  
     cy.klik('.page-body > .buttons > .button-1')
     cy.get('[class="validation-summary-errors"]').contains('The specified email already exists')
   })
   it ('Register with password with letter character number 5', () =>{
    //cy.visit(Cypress.env('Register_url'))
    cy.get('h1').should('have.text', 'Register')
    cy.get('#gender-female').check()
    cy.get('#FirstName').should('be.visible').type('Isnaeni')
    cy.get('#LastName').should('be.visible').type('rachmawati')
    cy.get('#Email').should('be.visible').type('rachmairma1@gmail.com')
    cy.get('#Password').should('be.visible').type('Irmaa')
    cy.get('#ConfirmPassword').should('be.visible').type('irmaa')
    //cy.get('#register-button').click()
    cy.klik('#register-button')
    cy.get('[class="field-validation-error"]').contains('The password should have at least 6 characters.') 
    //cy.get('.validation-summary-errors > ul > li').should('be.visible')
  })
  it ('Register with password with number 5 characters', () =>{
    //cy.visit(Cypress.env('Register_url'))
    cy.get('h1').should('have.text', 'Register')
    cy.get('#gender-female').check()
    cy.get('#FirstName').should('be.visible').type('Isnaeni')
    cy.get('#LastName').should('be.visible').type('rachmawati')
    cy.get('#Email').should('be.visible').type('rachmairma1@gmail.com')
    cy.get('#Password').should('be.visible').type('12345')
    cy.get('#ConfirmPassword').type('12345')
    cy.get('#register-button').click()
    cy.get('[class="field-validation-error"]').contains('The password should have at least 6 characters.') 
  })
  it('Register with password with letter character number 6', () =>{
   // cy.visit(Cypress.env('Register_url'))
    cy.get('h1').should('have.text', 'Register')
    cy.get('#gender-female').check()
    cy.get('#FirstName').should('be.visible').type('Isnaeni')
    cy.get('#LastName').should('be.visible').type('rachmawati')
    cy.get('#Email').should('be.visible').type('Isnaen339@gmail.com')
    cy.get('#Password').should('be.visible').type('Irmaaa')
    cy.get('#ConfirmPassword').should('be.visible').type('Irmaaa')
    cy.get('#register-button').click()
    cy.get('h1').contains('Register')
    //cy.get('.page-body > .buttons > .button-1').click() 
    cy.klik('.page-body > .buttons > .button-1')
    cy.get('[class="account"]').contains('Isnaen339@gmail.com')
  })
  it('Register with password with number 6 characters', () =>{
   // cy.visit(Cypress.env('Register_url'))
    cy.get('h1').should('have.text', 'Register')
    cy.get('#gender-female').check()
    cy.get('#FirstName').should('be.visible').type('Isnaeni')
    cy.get('#LastName').should('be.visible').type('rachmawati')
    cy.get('#Email').should('be.visible').type('rachma91@gmail.com')
    cy.get('#Password').should('be.visible').type('123456')
    cy.get('#ConfirmPassword').type('123456')
    cy.get('#register-button').click()
    cy.get('h1').contains('Register')
    //cy.get('.page-body > .buttons > .button-1').click() 
    cy.klik('.page-body > .buttons > .button-1')
    cy.get('[class="account"]').contains('rachma91@gmail.com')
  })
  it ('Register with a password combination of letters and numbers', () =>{
    //cy.visit(Cypress.env('Register_url'))
    cy.get('h1').should('have.text', 'Register')
    cy.get('#gender-female').check()
    cy.get('#FirstName').should('be.visible').type('Isnaeni')
    cy.get('#LastName').should('be.visible').type('rachmawati')
    cy.get('#Email').should('be.visible').type('irma345@gmail.com')
    cy.get('#Password').should('be.visible').type('Irmaa1')
    cy.get('#ConfirmPassword').should('be.visible').type('Irmaa1')
    cy.get('#register-button').click()
    cy.get('h1').contains('Register')
    //cy.get('.page-body > .buttons > .button-1').click() 
    cy.klik('.page-body > .buttons > .button-1')
    cy.get('[class="account"]').contains('irma34S@gmail.com')
  })

})
